dexterleng/vimac

ViMac-Swift/HideCursorGlobally.h, ViMac-Swift/HideCursorGlobally.m, ViMac-Swift/ViewControllers/ScrollModeViewController.swift, ViMac-Swift/VimacBridgingHeader.h, Vimac.xcodeproj/project.pbxproj
#71 
An issue I'm encountering is when you programmatically move the cursor while it is hidden you can't reliably make it visible again :/
Right click makes it appear again.
=> Hide Cursor and center it during Scroll mode

ViMac-Swift/ModeCoordinator.swift, ViMac-Swift/Utils.swift
=> Show hints for extra menu bar items

ViMac-Swift/AppDelegate.swift, ViMac-Swift/ModeCoordinator.swift, ViMac-Swift/Utils.swift
=> Show hints for Notification Center alerts

ViMac-Swift/AlphabetHints.swift, ViMac-Swift/Base.lproj/Main.storyboard, ViMac-Swift/Utils.swift, ViMac-Swift/Windows/Preferences/PreferencesGeneralViewController.swift
=> Customize hint characters

ViMac-Swift/AlphabetHints.swift, ViMac-Swift/UserPreferences.swift, ViMac-Swift/Utils.swift, ViMac-Swift/ViewControllers/HintModeViewController.swift, ViMac-Swift/ViewControllers/ScrollModeViewController.swift, ViMac-Swift/Windows/Preferences/HintModePreferenceViewController.swift, ViMac-Swift/Windows/Preferences/ScrollModePreferenceViewController.swift, Vimac.xcodeproj/project.pbxproj
Validation/Default value logic is scattered and copy-pasted everywhere. This PR creates a centralized struct UserPreferences from which Propertys can be read (raw or with default value) and saved.
=> Refactor preference reading

Carthage/Checkouts/LaunchAtLogin/LaunchAtLogin/copy-helper.sh, Vimac.xcodeproj/project.pbxproj
Can't seem to get it to work on AppCenter.
=> Remove codesigning of LaunchAtLoginHelper.app

Carthage/Checkouts/LaunchAtLogin/LaunchAtLogin/copy-helper.sh, Vimac.xcodeproj/project.pbxproj
Turns out it needs to be codesigned to build on dev. Had to add a cert to AppCenter.
=> Revert removal of LaunchAtLoginHelper.app; Add a team for code signing

ViMac-Swift/Services/QueryWebAreaService.swift, ViMac-Swift/Services/QueryWindowService.swift, ViMac-Swift/Utils.swift, ViMac-Swift/ViewControllers/HintModeViewController.swift, Vimac.xcodeproj/project.pbxproj
Expect super faster webkit and electron performance :)
=> Use AXUIElementsForSearchPredicate on AXWebArea for massive web performance boost

ViMac-Swift/HideCursorGlobally.m, ViMac-Swift/ViewControllers/HintModeViewController.swift
=> Hide Cursor and revert cursor position in Hint mode; Make HideCursorGlobally idempotent

ViMac-Swift/Services/QueryWindowService.swift
=> Use AXVisibleRows to fetch children of AXOutline and AXTable

ViMac-Swift/ViewControllers/HintModeViewController.swift
=> Fix crash when typing before hints are queried

ViMac-Swift/HintModeInputListener.swift, ViMac-Swift/ViewControllers/HintModeViewController.swift
=> HintModeInputListener - do not filter out non alpha-numerical events

ViMac-Swift/Accessibility/HintMode/QueryMenuBarExtrasService.swift, ViMac-Swift/AppDelegate.swift
=> Set Accessibility API timeout

ViMac-Swift/AppDelegate.swift
=> Fix hint/scroll mode not working on Vimac launch until window change

ViMac-Swift/StatusItemManager.swift, ViMac-Swift/Windows/Preferences/BindingsPreferenceViewController.swift, ViMac-Swift/Windows/Preferences/GeneralPreferenceViewController.swift, ViMac-Swift/Windows/Preferences/HintModePreferenceViewController.swift, ViMac-Swift/Windows/Preferences/PreferencesPaneIdentifiers.swift, ViMac-Swift/Windows/Preferences/ScrollModePreferenceViewController.swift, Vimac.xcodeproj/project.pbxproj
This is to prepare for adding key sequence support.
=> Move keyboard shortcuts preferences to Bindings tab

ViMac-Swift/ModeCoordinator.swift
Closes #282 
#214  still persists:
=> Actually fix hint mode in fullscreen

ViMac-Swift/GeometryUtils.swift, ViMac-Swift/ModeCoordinator.swift, ViMac-Swift/Utils.swift, ViMac-Swift/ViewControllers/HintModeViewController.swift, ViMac-Swift/ViewControllers/ScrollModeActiveViewController.swift, Vimac.xcodeproj/project.pbxproj
=> Fix hint and scroll mode positioning issues

ViMac-Swift/Utils.swift
=> Change default shortcuts to CTRL-F and CTRL-J

ViMac-Swift/Bindings/BindingsPreferenceViewController.swift, ViMac-Swift/Preferences/GeneralPreferenceViewController.swift, ViMac-Swift/Preferences/HintModePreferenceViewController.swift, ViMac-Swift/Preferences/ScrollModePreferenceViewController.swift
=> Add SF icons in Preferences

ViMac-Swift/Accessibility/AXEnhancedUserInterfaceActivator.swift, ViMac-Swift/Accessibility/AXManualAccessibilityActivator.swift, ViMac-Swift/Accessibility/QueryScrollAreasService.swift, ViMac-Swift/AppDelegate.swift, ViMac-Swift/Bindings/BindingsPreferenceViewController.swift, ViMac-Swift/Bindings/BindingsRepository.swift, ViMac-Swift/Extensions/ObservableType.swift, ViMac-Swift/Preferences/ExperimentalPreferenceViewController.swift, ViMac-Swift/Preferences/PreferencesPaneIdentifiers.swift, ViMac-Swift/UserDefaults/UserDefaultsProperties.swift, ViMac-Swift/UserDefaults/UserDefaultsProperty.swift, ViMac-Swift/Utils.swift, Vimac.xcodeproj/project.pbxproj
=> Create experimental option to enable/disable AXManualAccessibility and AXEnhancedUserInterface

ViMac-Swift/Accessibility/HintMode/HintModeQueryService.swift
=> Constant hint text for menu bar items

ViMac-Swift/AppDelegate.swift, ViMac-Swift/Preferences/AboutPreferencesViewController.swift, ViMac-Swift/Preferences/PreferencesPaneIdentifiers.swift, ViMac-Swift/StatusItemManager.swift, Vimac.xcodeproj/project.pbxproj, docs/non-native-support.md
Todo:
- Links to Guides, GitHub, Bug report/feature suggestions...
=> Preferences - Add About tab

ViMac-Swift/Accessibility/HintMode/HintModeQueryService.swift, ViMac-Swift/ModeCoordinator.swift, ViMac-Swift/ViewControllers/HintModeViewController.swift
=> Show hints when frontmost app or frontmost window are not present

ViMac-Swift/ChunkyScroller.swift
=> Fix scrolling not working in some cases (e.g. Terminal)

ViMac-Swift/AppDelegate.swift, ViMac-Swift/Base.lproj/Main.storyboard
=> Do not open Preferences on app launch; Clean up AX Permission checking code

ViMac-Swift/Accessibility/HintMode/TraverseGenericElementService.swift
See:
https://stackoverflow.com/questions/66969764/macos-accessibility-api-kaxerrorattributeunsupported-when-querying-books-app
=> Use AXUIElementCopyAttributeValues to fetch an element's children

README.md, ViMac-Swift/AppDelegate.swift, ViMac-Swift/Modes/HintModeController.swift
=> Move cursor when Option is held while typing hint text

ViMac-Swift/KeySequenceListener.swift
If you use `jk` as a key sequence, holding down `j` for scroll in Vimium caused it to stop for a short while before continuing. This fixes it.
=> Fix key sequence implementation when holding down prefix.

README.md, ViMac-Swift/Activation/HoldKeyListener.swift, ViMac-Swift/Bindings/BindingsConfig.swift, ViMac-Swift/Bindings/BindingsPreferenceViewController.swift, ViMac-Swift/Bindings/BindingsRepository.swift, ViMac-Swift/GlobalEventTap.swift, ViMac-Swift/ModeCoordinator.swift, ViMac-Swift/UserDefaults/UserDefaultsProperties.swift, Vimac.xcodeproj/project.pbxproj, docs/manual.md
some unorganized notes:
- space key down, shift space key up
- all key ups are passed through -> the assumption here is that key ups don't do anything, so we don't handle them to reduce complexity
```
// r key down -> pass through
onEvent() called. state=nothing keyDown=true characters=Optional("r") modifiers=NSEventModifierFlags(rawValue: 256) isARepeat=false
transformed event. state=nothing keyDown=true characters=Optional("r") modifiers=NSEventModifierFlags(rawValue: 256) isARepeat=false
// space key down -> set timeout
onEvent() called. state=nothing keyDown=true characters=Optional(" ") modifiers=NSEventModifierFlags(rawValue: 256) isARepeat=false
setAwaitingKey() called
onEvent transformed to nil
// r key up -> suppressed
// should we pass through, or avoid setting time out if still …
```
=> Hold Space to activate Hint-mode
